name = "UplinkerProxy"
uuid = "9f7bffa5-43e6-40d1-87d3-a1e22959e320"
authors = ["emmac <emmaccode@gmail.com>"]
version = "0.1.0"

[deps]
ChiProxy = "ab0dfc58-5d1e-41aa-81db-6420f49808fb"
Toolips = "a47e2ad8-fcf7-417c-9746-32b9bdf220bd"

[compat]
ChiProxy = "0.1.0"
Toolips = "0.3.9"
